Ext.define('AM.model.DeviceRecordModel',{
    extend:'Ext.data.Model',
    fields:[
        {name:'id',type:'Long'},
        {name:'userId',type:'Long'},
        {name:'borrowerUsername',type:'String', mapping: 'borrowerUsername'},
        {name:'borrorDate',type:'String'},
        {name:'approvalDate',type:'String'},
        {name:'returnDate',type:'String'},
        {name:'detail',type:'String'},
        {name:'sysUser.id',type:'Long', mapping: 'sysUser.id'},
        {name:'sysUser.sysusername',type:'String', mapping: 'sysUser.sysusername'},
        {name:'device.id',type:'Long', mapping: 'device.id'},
        {name:'device.deviceno',type:'String', mapping: 'device.deviceno'},
        {name:'device.devicexh',type:'String', mapping: 'device.devicexh'},
        {name:'device.devCpu.cpuname',type:'String', mapping: 'device.devCpu.cpuname'},
        {name:'device.devType.typename',type:'String', mapping: 'device.devType.typename'},
        {name:'device.devManufacturer.manufacturername',type:'String', mapping: 'device.devManufacturer.manufacturername'},
        {name:'returnApprovalUserId',type:'Long'},
        {name:'returnApprovalUsername',type:'String', mapping: 'returnApprovalUsername'},
        {name:'returnApprovalDate',type:'String'},
    ],
})